### ISSUE TITLE
Package SpringerPE/firehose-to-syslog as custom ingestor

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-for-cloudfoundry#19]
We need a custom ingestor to consume CloudFoundry's Doppler Firehost (which is delivered via Websockets); and needs to authenticate with Cloud Foundry's UUA component.

The nice folks over at https://github.com/SpringerPE/firehose-to-syslog have just such a component; so lets just use that!

**Comment by mrdavidlaing** [comment]
@simonjohansson - Could you add some licensing info to https://github.com/SpringerPE/firehose-to-syslog please - ideally MIT or APACHE v2.

**Comment by simonjohansson** [comment]
@mrdavidlaing sure thing. All have a go at it on Monday, and keep implementing the events stuff you need.

**Comment by simonjohansson** [comment]
@mrdavidlaing added licence, will start working on the extra events today if no fires crop up :)

**Comment by mrdavidlaing** [comment]
@simonjohansson - thanks!  I'll take over packaging firehose-to-syslog into a bosh release

**Comment by simonjohansson** [comment]
@mrdavidlaing great!

Let me know if you need any help.

**Comment by mrdavidlaing** [comment]
Done - see https://github.com/logsearch/logsearch-for-cloudfoundry#adding-to-an-existing-cloud-foundry--logsearch-deployments
