### ISSUE TITLE
New proper release of firehose-to-syslog released.

### ISSUE THREAD

**Issue by simonjohansson** [logsearch/logsearch-for-cloudfoundry#29]
https://github.com/cloudfoundry-community/firehose-to-syslog/releases/tag/0.1.0

I also included precompiled binaries in the release to make the compile step easier and to remove the dep on go.

**Comment by mrdavidlaing** [comment]
@simonjohansson - until `firehose-to-syslog` is very stable, I think its best that we keep compiling from source so we can use bleeding edge versions.

But thanks for the heads up!
