### ISSUE TITLE
What about the reverse proxy for multi-tenancy & Kibana dashboards?

### ISSUE THREAD

**Issue by tyyko** [logsearch/logsearch-for-cloudfoundry#32]
As title, the proxy setup for multi-tenancy showed in the video seems to be the main feature of this new release! But there is no documentation about that!

How to do it?

It may be useful to share the kibana dashboards too! (better pre-packaged on the deployment but also as a link here can be good)

Thank you!

**Comment by bonzofenix** [comment]
@tyyko I found that app at `src/cf-app-logs` still have not been able to make it run yet. Do not know the permissions required by the uaa for it. See its manifest.yml requires a uaa client.

**Comment by mrdavidlaing** [comment]
@tyyko, @bonzofenix - I'm busy creating a bosh errand to deploy the cf-app-logs proxy; which should make this clearer.  Sorry for the confusion

**Comment by yatzek** [comment]
Hi,

Any progress on the bosh errand?

**Comment by mrdavidlaing** [comment]
@yatzek, @tyyko, @bonzofenix 

Please follow progress at https://github.com/logsearch/logsearch-for-cloudfoundry/issues/43 and https://github.com/logsearch/logsearch-for-cloudfoundry/pull/47
