### ISSUE TITLE
Publish bosh release into bosh.io or s3 or github release

### ISSUE THREAD

**Issue by drnic** [logsearch/logsearch-for-cloudfoundry#35]
Can you please upload final release tgz into bosh.io or s3 or github releases?

**Comment by shinji62** [comment]
Full release is there no ? https://logsearch-for-cloudfoundry-boshrelease.s3.amazonaws.com/boshrelease-logsearch-for-cloudfoundry-2.tgz

**Comment by drnic** [comment]
Thanks for linking URL to v4 release notes
