### ISSUE TITLE
Error unmarshaling app json: cannot unmarshal number into Go value of type string

### ISSUE THREAD

**Issue by drnic** [logsearch/logsearch-for-cloudfoundry#38]
I am deploying this bosh release v2 with v19 of logsearch; and the ingestor/0 is failing and in the ingestor_cloudfoundry-firehose logs I see:

```
Error unmarshaling app json: cannot unmarshal number into Go value of type string
```

Where/how do I go about debugging that?

in the _ctl it looks ok I guess:

```
    exec chpst -u vcap:vcap firehose-to-syslog \
        --domain=myorg.com \
        --skip-ssl-validation  \
        --user=admin \
        --password=ADMINPASS \
        --syslog-server=127.0.0.1:5514 \
        --events=LogMessage,Error,ContainerMetric \
        --boltdb-path=$TMP_DIR/firehose-to-syslog.cache.db \
        --cc-pull-time=60s \
         >>$LOG_DIR/$JOB_NAME.stdout.log \
         2>>$LOG_DIR/$JOB_NAME.stderr.log
```

**Comment by drnic** [comment]
Using CF v205

**Comment by drnic** [comment]
Pfft, can't find `Error unmarshaling` in any repos

**Comment by drnic** [comment]
Found that error string in go-cfclient repo

**Comment by drnic** [comment]
What versions of CF should logsearch-for-cloudfoundry work with?

Still confused about the error - it only seems like it might come from go-cfclient parsing the `/v2/apps` API. Not sure what issues that might cause.

**Comment by mrdavidlaing** [comment]
@drnic, I've had success with v205 and v207.

Can you try v3 of `logsearch-for-cloudfoundry` - it contains an updated `firehose-to-syslog`, which in turn contains an updated `go-cfclient`

https://logsearch-for-cloudfoundry-boshrelease.s3.amazonaws.com/boshrelease-logsearch-for-cloudfoundry-3.tgz

**Comment by drnic** [comment]
@mrdavidlaing I don't think the package got updated in v3; or something odd is happening - I upgraded to v3 but no new packages were compiled.

Also, when looking at the version in v3 of that package, it seems its also in v2 of the release https://github.com/logsearch/logsearch-for-cloudfoundry/search?utf8=%E2%9C%93&q=49f3d4997d4cd69676bc6e76de678aaebb21c02b

Ideas?

**Comment by drnic** [comment]
The diff between v2 and v3:

```diff
diff releases/logsearch-for-cloudfoundry/logsearch-for-cloudfoundry-{2,3}.yml
3,6c3,6
< - name: golang1.4
<   version: f57ddbc8d55d7a0f08775bf76bb6a27dc98c7ea7
<   fingerprint: f57ddbc8d55d7a0f08775bf76bb6a27dc98c7ea7
<   sha1: 1514f2765093eb9e912469fbf9887e73ae2d2412
---
> - name: cli
>   version: 2bb59769970d6b9c5c478984e622d4bd24ea4750
>   fingerprint: 2bb59769970d6b9c5c478984e622d4bd24ea4750
>   sha1: 0e7a305a3036bb26eca79f27d8c128242b022435
13a14,23
> - name: golang1.4
>   version: f57ddbc8d55d7a0f08775bf76bb6a27dc98c7ea7
>   fingerprint: f57ddbc8d55d7a0f08775bf76bb6a27dc98c7ea7
>   sha1: 1514f2765093eb9e912469fbf9887e73ae2d2412
>   dependencies: []
> - name: kibana-for-cf
>   version: 206c83ec5695bb091b97f97a0884e5db04af5f43
>   fingerprint: 206c83ec5695bb091b97f97a0884e5db04af5f43
>   sha1: 54dd42677c96fb33c20f0d990cc99ea6ae6c09f1
>   dependencies: []
18a29,32
> - name: push-kibana
>   version: d0646997c946506699518c4e3f3916c1a8bf4b44
>   fingerprint: d0646997c946506699518c4e3f3916c1a8bf4b44
>   sha1: e2e48e2891cd3026fd1d18cc133cd89c52629337
23c37
< commit_hash: b594109e
---
> commit_hash: 3e837210
26c40
< version: '2'
---
> version: '3'
```

**Comment by simonjohansson** [comment]
@drnic we will have to make a better effort of documenting in firehose-to-syslog which release works with which cf-release. THere have been many breaking changes. :(

**Comment by mrdavidlaing** [comment]
@drnic, @simonjohansson - we really need a Concourse build pipeline for making logsearch-for-cloudfoundry releases; since I keep making these dumb errors.

Either of you interested in getting involved in making one?

**Comment by mrdavidlaing** [comment]
@drnic  not sure why your diff isn't picking up this change - https://github.com/logsearch/logsearch-for-cloudfoundry/commit/ec5db414a8a0325559d2d6596fe022d27098bdcd#diff-eb92f1fbaab68668b8fae8dba7254bf3

Has it got something to do with it being on a branch, which I have subsequently merged into `master`?

**Comment by drnic** [comment]
@mrdavidlaing my diff was a diff between v2.yml and v3.yml; see that the same version/fingerprint exists in v2 for `firehose-to-syslog` package:

* v2 https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/logsearch-for-cloudfoundry-boshrelease/releases/logsearch-for-cloudfoundry/logsearch-for-cloudfoundry-2.yml#L9
* v3 https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/logsearch-for-cloudfoundry-boshrelease/releases/logsearch-for-cloudfoundry/logsearch-for-cloudfoundry-3.yml#L9

Somehow the package didn't get bumped during creation of bosh release?

**Comment by drnic** [comment]
@simonjohansson its tricky when other ppl show up and start trying to use your stuff :D

**Comment by drnic** [comment]
I've resolved my original issue - the log error was a red herring. I thought indexes were created once data started coming in; I didn't realise that data was being ingested just fine; and I need to create an index.

**Comment by mrdavidlaing** [comment]
@drnic - I'm pleased you solve your error; but confused with your need to create an index.  If you're talking about Elasticsearch indexes; these should definately be created automatically (a new one should be created every day, when logs with that day's timestamp start flowing in)

**Comment by rkoster** [comment]
I think he ment `Index Pattern`, this will probably not be necessary once the [push-kibana](https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/logsearch-for-cloudfoundry-boshrelease/jobs/push-kibana/templates/bin/run#L47) errand is included in a final release.
