### ISSUE TITLE
Please tag when you cut bosh releases

### ISSUE THREAD

**Issue by drnic** [logsearch/logsearch-for-cloudfoundry#39]
It's hard to figure out exactly what is in a bosh release (e.g v2) without a git tag (which feeds into .gitmodule)

**Comment by drnic** [comment]
Thanks at least for putting `v2` in one of the commit msgs edb3a858d61a5afb989bf3cdac5717107f5d4b63

**Comment by mrdavidlaing** [comment]
My bad.  Have added a v3 tag, and will look at formalising the release process going forward
