### ISSUE TITLE
release tgz accidentally added to git repo

### ISSUE THREAD

**Issue by drnic** [logsearch/logsearch-for-cloudfoundry#42]
An 80+ Mb release tgz was accidentally added to the repo https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/logsearch-for-cloudfoundry-boshrelease/releases/logsearch-for-cloudfoundry/logsearch-for-cloudfoundry-3.tgz

Can we remove it?

a) anyone can recreate this with `bosh create release --with-tarball <path/to/release.yml>`
b) people can download it from bosh.io when you get it added there

**Comment by dpb587** [comment]
I think I did something strangely in the process, but all the other filter-branch commands from docs were rewriting the whole repository history and not just these commits. So, I've gone ahead with pushing this anyway given this whole thing is already a naughty git action.

Affected commits have been rewritten...

    old commit                               rewritten to                             notes
    2d812a80a0faa691efaf0e43bf7b409dbcb94a88 838770e8ee65f1608b65873b1b59f24aa627b51d
    ad7adebafc9bc49874d18b2442e2a14fc664d417 96a91b5029c9e1aa7f7c262615a036d0c89a035e
    d06a453ee1d45aef3859cff3c742e2a0bdaa51b8 3170b3b11e7ab671ce79ef8989541b7220be28d0 refs/tags/v3
    ec5db414a8a0325559d2d6596fe022d27098bdcd 3170b3b11e7ab671ce79ef8989541b7220be28d0


**Collaborators...**

If your local branches include these commits, you **must not merge**. Instead, [rebase](http://git-scm.com/book/en/Git-Branching-Rebasing) your changes onto the rewritten commit. The following may be helpful...

First, be sure you have fetched the rewritten repository.

    $ git fetch

If you see the following, you'll need to rebase.

    $ git status
    Your branch and 'origin/master' have diverged,
    and have 5 and 3 different commits each, respectively.

You can check to see which old commit you have using the following.

    $ git rev-parse $( git rev-list origin..HEAD | tail -n1 )^1
    ec5db414a8a0325559d2d6596fe022d27098bdcd

Use the command's output and the table above to lookup the new commit. Then use those values in your rebase...

    $ git rebase --onto 3170b3b11e7ab671ce79ef8989541b7220be28d0 ec5db414a8a0325559d2d6596fe022d27098bdcd

You should then see...

    $ git status
    Your branch is ahead of 'origin/master' by 2 commits.

**Comment by dpb587** [comment]
(Also, thanks for creating the issue about it)
