### ISSUE TITLE
Add Authentication via kibana-server plugin using CF UAA OAuth2

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-for-cloudfoundry#43]
Core logsearch-boshrelease intentionally doesn't include authentication ( [discussion](https://github.com/logsearch/logsearch-boshrelease/pull/124#issuecomment-100312238) ); expecting to be locked away via firewall rules.

The [`push-kibana` errand](https://github.com/logsearch/logsearch-for-cloudfoundry/tree/master/logsearch-for-cloudfoundry-boshrelease/jobs/push-kibana) deploys an instance of Kibana to CF as a way to "open a public route" to a logsearch cluster.

This is a good place to add authentication, since we can leverage CF's UAA infrastructure & SSL, and the "malicious request" filtering provided by the kibana-server elasticsearch proxy.

Kibana v4.2 formalises a way to include plugins in the kibana-server - see https://github.com/elastic/kibana/pull/3714 - based on http://hapijs.com/.  Adding OAuth2 authentication to Hapi applications is a [solved problem](http://www.sitepoint.com/oauth-integration-using-hapi/), so adding a kibana-server plugin to handle authentication should be straight forward.

**Comment by shinji62** [comment]
I thought the user authentification was already in place.
"cf-users (those deploying apps to the CF cluster) see a tenanted view of the doppler firehose data stored in Logsearch for just the apps in spaces they are members of. They access the data via an app deployed on CF, and are required to authenticated against the CF's UAA component using the same credentials they would use to interact via the cf CLI tool. "

**Comment by mrdavidlaing** [comment]
@shinji62,  You are correct; we currently have a spring app that runs on CF as a "multi-tenant" proxy; but I think this should be depreciated in the interests of fewer technology stacks to maintain, since with Kibana's new plugin system the auth functionality (and eventually the multi-tenant functionality) can be implemented in Kibana itself

**Comment by shinji62** [comment]
If this can reduce complexity .. not sure this plugin support authentication based on logs, ex this user can access to this application logs.
