### ISSUE TITLE
It's impossible to install ingestor_cloudfoundry-firehose  and logsearch/ingestor_syslog on the same VM

### ISSUE THREAD

**Issue by Ykisialiou** [logsearch/logsearch-for-cloudfoundry#45]
Hello. While trying create a single job for ingestors (logsearch/ingestor_syslog and  logsearch-for-cloudfoundry/ingestor_cloudfoundry-firehose)  i'm receiving this error. Shouldn't this templates be able to live on single bosh job? Thank you. 

Error 80011: Package name collision detected in job `ingestor': template `logsearch/ingestor_syslog' depends on package `logsearch/logstash', template `logsearch-for-cloudfoundry/ingestor_cloudfoundry-firehose' depends on `logsearch-for-cloudfoundry/logstash'. BOSH cannot currently collocate two packages with identical names from separate releases.

**Comment by mrdavidlaing** [comment]
I don't see why not - its just a case of renaming the `logsearch-for-cloudfoundry/logstash` package to something like `logsearch-for-cloudfoundry/logstash_for_ingestor_cloudfoundry-firehose`

Feel free to submit a PR to make that change.

**Comment by Ykisialiou** [comment]
Thank you for quick response. I'll do after some testing

**Comment by mrdavidlaing** [comment]
Closing in favour of #63
