### ISSUE TITLE
Dashboard  is RELP specific 

### ISSUE THREAD

**Issue by bonzofenix** [logsearch/logsearch-for-cloudfoundry#48]
Hi David,

Our doppler stream logs though TCP; this sets the type of the log as __syslog__ instead of __relp__.
The [json file for the dasboards](https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/target/kibana4-dashboards.json) is relp specific.
Would you accept a PR with the json file turned into an erb and a property for the ingestor-for-cloudfoundry that sets the protocol?

Please let us know so that we get to work right away.

Thanks

@bonzofenix && @cloud-dude

**Comment by mrdavidlaing** [comment]
First, thanks for picking up on this error and starting a discussion.

There should be a simpler way to solve this problem by filtering the logs shown in the dashboard by something that isn't protocol specific.

The queries behind the CF dashboards use a high level filter: `_type:"relp_cf"`.  Looking at the [filters](https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/src/logstash-filters/snippets/vcap.conf#L43), I think all the logs we want can better be found by filtering for `tag:cloudfoundry_vcap`

Could you try that approach first; and if it works, I'd happily accept a PR.

Talking about PRs I'll need a signed [CLA](https://github.com/logsearch/licensing) before I can merge.

**Comment by bonzofenix** [comment]
Today we worked on this. Your recommendation worked great. Unfortunately not all dashboards work out of the box for us. For example we receive Nats message with `source:Nats::Dea` instead of  `source:NatsStreamForwarder`. We also do not receive the app_name, we are using the app_id instead. We might be in an older version of CF. We will try to track this down tomorrow so that we can document for which cf version this dashboards actually work out of the box. if not we will submit a PR for the `tag:cloudfoundry_vcap` issue and maybe the app_id change if you agree.

cc: @cloud-dude , @malston

**Comment by shinji62** [comment]
For the application name nothing to do with CF, logsearch use https://github.com/cloudfoundry-community/firehose-to-syslog to ingest application logs and this app name logic is there.

But you need to supply an user with admin right or at least able to lookup user within the cc api.

**Comment by mrdavidlaing** [comment]
@bonzofenix - FYI, we're using CF v205.

It appears that tying the standard dashboards to data in the log messages themselves is a bad idea.

I think that instead we should filter based on tags that we add during the parsing stage (like  `tag:cloudfoundry_vcap`).  That way we can adjust the filters to ensure that log messages from different versions of CF get the same tag, even if the data changes slightly.

Thoughts?

**Comment by malston** [comment]
Perhaps the refresh token has expired?

**Comment by bonzofenix** [comment]
Ok this [PR](https://github.com/logsearch/logsearch-for-cloudfoundry/pull/49) fixes the relp issue. @shinji62 you were right about the apps_name issue, Upgrading and using the push-kibana errand fix it for us.

We will open if necessary a new issue for the NatsStreamForwarder once we identify the cause.

@cloud-dude && @bonzofenix
