### ISSUE TITLE
Dashboards are not persistent after app is restart or redeploy

### ISSUE THREAD

**Issue by cloud-dude** [logsearch/logsearch-for-cloudfoundry#52]
Currently the dashboard import relies on the bosh push kibana errand. A possible solution to this would be to import through the manifest with the run command.

@mrdavidlaing We are thinking implementing this feature. What are your thoughts on the implementation?

Thanks,
@cloud-dude & @bonzofenix

**Comment by mrdavidlaing** [comment]
@cloud-dude - Are you talking about how the `push-kibana` errand will overwrite the standard dashboards, or the fact that there is no way to "add" dashboards to the `push-kibana` errand?

For the case of overwrite; I think we should rename all the standard dashboards to have a `ro_` prefix, and then implement a plugin to prevent saves to them.

For the "how to add" case, there is a feature coming in `logsearch-boshrelease` - https://github.com/logsearch/logsearch-boshrelease/pull/144 - which implements the ability to specify dashboards as part of the manifest; so lets just wait for that.  (Should be part of logsearch v21, scheduled for release next week)

**Comment by mrdavidlaing** [comment]
@cloud-dude & @bonzofenix,

I'm reworking how the dashboards are stored  / imported over at #67.  Lets move this conversation over there.
