### ISSUE TITLE
Cannot access Kibana

### ISSUE THREAD

**Issue by pawel2-grape** [logsearch/logsearch-for-cloudfoundry#62]
Hi,
I've deployed logsearch-boshrelease v21 and then the logsearch-for-cloudfoundry v6.
After '<b>bosh run errand push-kibana</b>' I have new app (that's good) in new space - elk-for-pcf (that's also can be good).
The problem is I cannot access to this app by <b>logs.run.&lt;MY_ELASTIC_IP&gt;.xip.io</b>.
There is a message <i>"Uh oh. Something went amiss."</i>
And when I log in on the page <b>login.run.&lt;MY_ELASTIC_IP&gt;.xip.io</b> as admin and then try to access Kibana the message is:
<i>"Authorization Request Error There was an error. The request for authorization was invalid."</i>

How can I debug what is wrong and how can I access to pushed kibana app...
I will be grateful for help.

**Comment by mrdavidlaing** [comment]
@pawel2-grape - Were you able to resolve this error, or are you still stuck?

If so, can you grab some of the logs from the Kibana logs app around the time when the error occurs

```
cf logs logs
```

**Comment by pawel2-grape** [comment]
I've deployed logsearch-boshrelease and that's all. Now I can access to Kibana 3 by private address of kibana machine on port 80 or 5601 (for Kibana 4).
I didn't resolve this problem, but now I'm using different manifest of CF and deal with something else.
But for sure I will return to this. Maybe I had a knowledge gap and now everything will be good...
You can close this issue for now, I will reopen it if it return.
Sorry for bad English and thanks for response.

**Comment by mrdavidlaing** [comment]
Good luck!
