### ISSUE TITLE
Document minimum permissions required for firehose user

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-for-cloudfoundry#74]
The ingestor_cloudfoundry-firehose job uses the  [`properties.cloudfoundry.firehose_user` to connect to the CF firehose and to connect to the CF Cloud Controller to fetch information about which spaces/orgs apps belong in](https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/logsearch-for-cloudfoundry-boshrelease/jobs/ingestor_cloudfoundry-firehose/spec#L27)

Currently we default to using the standard `admin` user; but we should use a specific user with the minimum required permissions.

This issue is about figuring out what those permissions are, and documenting them.

**Comment by mrdavidlaing** [comment]
The `properties.cloudfoundry.firehose_user` spec property is passed through to the  [https://github.com/cloudfoundry-community/firehose-to-syslog library](https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/logsearch-for-cloudfoundry-boshrelease/jobs/ingestor_cloudfoundry-firehose/templates/bin/ingestor_cloudfoundry-firehose_ctl#L75), so that will dictate the permissions needed.

My suspicion is that these include:

* `cloud_controller.read`
* `doppler.firehose`

@shinji62, @simonjohansson - can you shed any further light on the permissions required?

**Comment by shinji62** [comment]
We need to be able to read / call the API for the application name.

**Comment by mrdavidlaing** [comment]
@shinji62 - is that not covered by `cloud_controller.read` ?

**Comment by shinji62** [comment]
I am worried this one only implies org space of the user...

**Comment by shinji62** [comment]
```
cloud_controller.read	Allows read access to all resources the user is authorized to read
cloud_controller.write	Allows write access to all resources the user is authorized to update / create / delete
```

**Comment by mrdavidlaing** [comment]
@shinji62 - excellent point; I wonder whether there is a scope permission that grants access to read data from all orgs, or whether you have to be a user who is a member of those orgs.

@simonjohansson - you have any idea?

**Comment by shinji62** [comment]
Member who have access to these orgs should work with .read

but .admin is more comfortable :)
Most of other tile use admin credentials anyway

**Comment by mrdavidlaing** [comment]
@shinji62 - for new we'll just connect with the admin user
