### ISSUE TITLE
No permission separation from normal/admin users

### ISSUE THREAD

**Issue by wkielas** [logsearch/logsearch-for-cloudfoundry#77]
I have created a new CF user with only the OrgManager permission for one organization. 
When logging in to the `logs` app and authenticating myself as the new CF user I see all of the Cloud Foundry logs, including nats/router logs.

How does the current version of the Kibana authentication plugin offer multi-tenancy? Is there any way to create a user that will be restricted only to seeing his own app logs?

**Comment by mrdavidlaing** [comment]
This feature is broken in the current release; it will be added back as soon as Kibana 4.2 becomes stable.
